[package]
name = "cryptoRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
near-sdk = "4.0.0"
hex = "0.4.3"
sha2 = "0.10.6"
hex-literal = "0.3.4"
hmac = "0.12.1"

